name: .NET Core Service CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # ← Add this block to allow manual runs with inputs
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Debug'
      solution-name:
        description: 'Solution file (e.g. KycAggregatorService.sln)'
        required: true
        default: 'KycAggregatorService.sln'
      test-project-path:
        description: 'Test project .csproj path'
        required: true
        default: 'KycAggregatorService/UnitTests/UnitTests.csproj'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        # if triggered manually, matrix.configuration will be overridden
        configuration: [ "${{ github.event.inputs.configuration }}" ]

    env:
      # pulled from the manual inputs
      Solution_Name: ${{ github.event.inputs.solution-name }}
      Test_Project_Path: ${{ github.event.inputs.test-project-path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build
        run: dotnet build ${{ env.Solution_Name }} \
              --configuration ${{ matrix.configuration }} \
              --no-restore

      - name: Test
        run: dotnet test ${{ env.Test_Project_Path }} \
              --configuration ${{ matrix.configuration }} \
              --no-build
