name: .NET Core Service CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [ Debug, Release ]

    # <-- static defaults so they're never empty
    env:
      Solution_Name: KycAggregatorService.sln
      Test_Project_Path: KycAggregatorService/UnitTests/UnitTests.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        # expands to: dotnet restore KycAggregatorService.sln
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build
        # expands to: dotnet build KycAggregatorService.sln --configuration Debug --no-restore
        run: dotnet build ${{ env.Solution_Name }} \
              --configuration ${{ matrix.configuration }} \
              --no-restore

      - name: Test
        # expands to: dotnet test KycAggregatorService/UnitTests/UnitTests.csproj --configuration Debug --no-build
        run: dotnet test ${{ env.Test_Project_Path }} \
              --configuration ${{ matrix.configuration }} \
              --no-build
